### ISSUE TITLE
deleteAll not working in Internet Explorer

### ISSUE THREAD

**Issue by dtslvr** [tameemsafi/typewriterjs#22]
I have found an issue with deleteAll in _Internet Explorer 11_. When I apply `deleteAll()`, it's just ignored and the next string is just appended. In the developer tools, there is an error like `Object doesn't support property or method 'remove'`.
I could even reproduce it in this example: https://jsfiddle.net/mv612vrf/1702

Do you have an idea how to solve it?

**Comment by realgs** [comment]
It is because .remove() function is not supported by IE.
You can use jquery or augmenting native DOM functions instead.
@tameemsafi I can take a look at this issue if you want me to.

**Comment by tameemsafi** [comment]
@realgs that would be great if you can do that and make a pull request

**Comment by dtslvr** [comment]
> It is because .remove() function is not supported by IE.

Yes, that's it. I could fix it in my project by adding the [dom4 polyfill](https://github.com/WebReflection/dom4).

**Comment by tameemsafi** [comment]
You can also import from corejs library.
https://github.com/zloirock/core-js/blob/master/README.md

**Comment by realgs** [comment]
I wanted to test my solution before PR, how do you run your project? There are no instructions in readme.md. Which local server do you use? 

I tried building the project with yarn run build:dev and then running live-server on chained-example but  there's a 404 error on dist/core.js file. From google I can suppose it might be related to Grunt. If I manually copy the dist/core.js file to examples/chained-example/ and link it adequately everything works fine.

**Comment by tameemsafi** [comment]
You need to use some sort of server. I would recommend `http-server` on npm and then run that command on the main repo directory locally. That way you will have access to `localhost:8080/examples` folder.

Also I fixed the issue now in `v2.5.0`. I just imported a polyfill for `node.remove`.

**Comment by sebastianjung** [comment]
For me the problem (or some other?) still exists. When using .deleteChars(x) IE11 gives me the following error:
"Uncaught Type: Cannot Read Property RemoveChild of Null"

This problem does not exist in version 2.5.0 but does in 2.5.1 and 2.5.2. Hope this helps.

**Comment by sebastianjung** [comment]
I am also facing the problem, that too many characters are deleted when using .deleteChars(). See here dev.pds.ultrabold.de

**Comment by danielhaim1** [comment]
I also tested `deleteChars(#)` as well as adding `DOM4` to polyfill. Unfortunately neither methods worked for me and the bug still occurs for IE11.
